version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dispatchai-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/dispatchai
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_EXPIRE_TIME=${JWT_EXPIRE_TIME}
    networks:
      - dispatchai-network
    volumes:
      - ./:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    container_name: dispatchai-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - dispatchai-network

networks:
  dispatchai-network:
    driver: bridge

volumes:
  mongodb_data:
